---
title: "Prediction On Resale Flat Prices"
output: html_document
---

# Modeling

```{r}
library(dplyr)
```

```{r}
df <- read.csv("../data/data_clean.csv", stringsAsFactors = TRUE)
df$year <- factor(df$year)
df$month <- factor(df$month)
df$block <- factor(df$block)
```

```{r}
head(df)
```

```{r}
str(df)
```

```{r}
colnames(df)
```

## Train-Test Split

```{r}
sort(unique(df$year))
```

```{r}
train_set <- df %>% filter(year < 2021)
test_set <- df %>% filter(year == 2021)
```

```{r}
head(train_set)
```

```{r}
head(test_set)
```

## Linear Regression

```{r}
# TODO
```

## Polynomial Regression

```{r}
# TODO
```

## Time Series Regression

```{r}
# TODO
```

## Lasso Regression (L1 Regularization)

```{r}
# TODO
```

## Ridge Regression (L2 Regularization)

```{r}
# TODO
```

## Elastic Net Regression

```{r}
# TODO
```

## Decision Tree Regression

```{r}
# TODO
```

## Random Forest Regression

```{r}
# TODO
```

## Support Vector Regression

```{r}
# TODO
```

# Model Selection

```{r}
# Compare all models
# Choose the best model
# Train the final model with full dataset
# Save model
```

