---
title: "Modeling - Regularization"
output: html_notebook
---

## Imports

```{r}
library(dplyr)
library(glmnet)
```

## Preparation

```{r}
df <- read.csv("../data/data_clean.csv", stringsAsFactors = TRUE)
```

```{r}
str(df)
```

```{r}
df$year <- factor(df$year)
```

```{r}
str(df)
```

## Helper Functions

```{r}
get_metrics <- function(y_actual, y_predict) {
  mae <- mean(abs(y_actual - y_predict))
  mse <- mean((y_actual - y_predict)^2)
  rmse <- sqrt(mse)
  
  sse <- sum((y_actual - y_predict)^2)
  sst <- sum((y_actual - mean(y_actual))^2)
  rsq <- 1 - (sse / sst)
  
  metrics <- data.frame(MAE = mae, MSE = mse, RMSE = rmse, "R-squared" = rsq)
  return (metrics)
}
```

```{r}
# Helper function to scale floor_area_sqm to z-score
scale_floor_area_sqm <- function(floor_area_sqm) {
  mean_floor_area_sqm <- mean(train_set$floor_area_sqm)
  std_floor_area_sqm <- sd(train_set$floor_area_sqm)
  z_score <- (floor_area_sqm - mean_floor_area_sqm) / std_floor_area_sqm
  return (z_score)
}
```

```{r}
# Helper function to scale remaining_lease to z-score
scale_remaining_lease <- function(remaining_lease) {
  mean_remaining_lease <- mean(train_set$remaining_lease)
  std_remaining_lease <- sd(train_set$remaining_lease)
  z_score <- (remaining_lease - mean_remaining_lease) / std_remaining_lease
  return (z_score)
}
```

```{r}
# Helper function to scale max_floor_lvl to z-score
scale_max_floor_lvl <- function(max_floor_lvl) {
  mean_max_floor_lvl <- mean(train_set$max_floor_lvl)
  std_max_floor_lvl <- sd(train_set$max_floor_lvl)
  z_score <- (max_floor_lvl - mean_max_floor_lvl) / std_max_floor_lvl
  return (z_score)
}
```

## Train-Test Split

```{r}
train_set <- df %>% filter(year != 2021)
test_set <- df %>% filter(year == 2021)
```

```{r}
all_columns <- colnames(df)
excluded_columns <- c("block", "street_name", "year", "month", "price_per_sqm", "region", "resale_price")
selected_features <- all_columns[!all_columns %in% excluded_columns]
selected_features
```

```{r}
g_X_train_temp <- train_set %>% select(all_of(selected_features))
g_X_train_temp$floor_area_sqm <- scale_floor_area_sqm(g_X_train_temp$floor_area_sqm)
g_X_train_temp$remaining_lease <- scale_remaining_lease(g_X_train_temp$remaining_lease)
g_X_train_temp$max_floor_lvl <- scale_max_floor_lvl(g_X_train_temp$max_floor_lvl)
g_X_train <- model.matrix(~ ., g_X_train_temp)[,-1]

g_X_test_temp <- test_set %>% select(all_of(selected_features))
g_X_test_temp$floor_area_sqm <- scale_floor_area_sqm(g_X_test_temp$floor_area_sqm)
g_X_test_temp$remaining_lease <- scale_remaining_lease(g_X_test_temp$remaining_lease)
g_X_test_temp$max_floor_lvl <- scale_max_floor_lvl(g_X_test_temp$max_floor_lvl)
g_X_test <- model.matrix(~ ., g_X_test_temp)[,-1]

g_y_train <- train_set$resale_price
g_y_test <- test_set$resale_price
```

## Lasso Regression (L1 Regularization)

```{r}
set.seed(101)
lasso_model <- cv.glmnet(g_X_train, g_y_train, alpha = 1, type.measure = "mse", family = "gaussian")
```

```{r}
lasso_model
```

```{r}
# Best lambda value
lasso_model$lambda.1se
```

```{r}
lasso_y_pred <- predict(lasso_model, newx = g_X_test, s = lasso_model$lambda.1se)
```

```{r}
lasso_metrics <- get_metrics(g_y_test, lasso_y_pred)
lasso_metrics
```

## Ridge Regression (L2 Regularization)

```{r}
set.seed(101)
ridge_model <- cv.glmnet(g_X_train, g_y_train, alpha = 0, type.measure = "mse", family = "gaussian")
```

```{r}
ridge_model
```

```{r}
# Best lambda value
ridge_model$lambda.1se
```

```{r}
ridge_y_pred <- predict(ridge_model, newx = g_X_test, s = ridge_model$lambda.1se)
```

```{r}
ridge_metrics <- get_metrics(g_y_test, ridge_y_pred)
ridge_metrics
```

## Elastic Net Regression

```{r}
# Experiment with a range of alpha values.
set.seed(101)

elastic_alpha_list <- c(0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1)
elastic_lambda_list <- numeric()
elastic_mse_list <- numeric()

for (i in elastic_alpha_list) {
  elastic_temp_model <- cv.glmnet(g_X_train, g_y_train, alpha = i, type.measure = "mse", family = "gaussian")
  elastic_lambda_list <- c(elastic_lambda_list, elastic_temp_model$lambda.1se)
  
  elastic_temp_y_pred <- predict(elastic_temp_model, newx = g_X_test, s = elastic_temp_model$lambda.1se)
  elastic_temp_mse <- mean((g_y_test - elastic_temp_y_pred)^2)
  elastic_mse_list <- c(elastic_mse_list, elastic_temp_mse)
}

elastic_result <- data.frame(alpha = elastic_alpha_list, lambda = elastic_lambda_list, mse = elastic_mse_list)
elastic_result
```

```{r}
# Best alpha value
elastic_min_mse <- elastic_result %>% filter(mse == min(mse)) %>% head(1)
elastic_best_alpha <- elastic_min_mse$alpha
elastic_best_alpha
```

```{r}
# Create model with the best alpha value
set.seed(101)
elastic_model <- cv.glmnet(g_X_train, g_y_train, alpha = elastic_best_alpha, type.measure = "mse", family = "gaussian")
```

```{r}
elastic_model
```

```{r}
# Best lambda value
elastic_model$lambda.1se
```

```{r}
elastic_y_pred <- predict(elastic_model, newx = g_X_test, s = elastic_model$lambda.1se)
```

```{r}
elastic_metrics <- get_metrics(g_y_test, elastic_y_pred)
elastic_metrics
```

## Elastic Net Regression (Tuning)

```{r}
# Experiment with a range of alpha values.
set.seed(101)

elastic_tune_alpha_list <- seq(0.01, 0.5, by=0.01)
elastic_tune_lambda_list <- numeric()
elastic_tune_mse_list <- numeric()

for (i in elastic_tune_alpha_list) {
  elastic_tune_temp_model <- cv.glmnet(g_X_train, g_y_train, alpha = i, type.measure = "mse", family = "gaussian")
  elastic_tune_lambda_list <- c(elastic_tune_lambda_list, elastic_tune_temp_model$lambda.1se)
  
  elastic_tune_temp_y_pred <- predict(elastic_tune_temp_model, newx = g_X_test, s = elastic_tune_temp_model$lambda.1se)
  elastic_tune_temp_mse <- mean((g_y_test - elastic_tune_temp_y_pred)^2)
  elastic_tune_mse_list <- c(elastic_tune_mse_list, elastic_temp_mse)
}

elastic_tune_result <- data.frame(alpha = elastic_tune_alpha_list, lambda = elastic_tune_lambda_list, mse = elastic_tune_mse_list)
elastic_tune_result
```

```{r}
# Best alpha value
elastic_tune_min_mse <- elastic_tune_result %>% filter(mse == min(mse)) %>% head(1)
elastic_tune_best_alpha <- elastic_tune_min_mse$alpha
elastic_tune_best_alpha
```

```{r}
# Create model with the best alpha value
set.seed(101)
elastic_tune_model <- cv.glmnet(g_X_train, g_y_train, alpha = elastic_tune_best_alpha, type.measure = "mse", family = "gaussian")
```

```{r}
elastic_tune_model
```

```{r}
# Best lambda value
elastic_tune_model$lambda.1se
```

```{r}
elastic_tune_y_pred <- predict(elastic_tune_model, newx = g_X_test, s = elastic_model$lambda.1se)
```

```{r}
elastic_tune_metrics <- get_metrics(g_y_test, elastic_tune_y_pred)
elastic_tune_metrics
```

## Results

```{r}
models <- c("Lasso", "Ridge", "Elastic Net", "Elastic Net (Tuned)")
metrics <- rbind(lasso_metrics, ridge_metrics, elastic_metrics, elastic_tune_metrics)
row.names(metrics) <- models
metrics
```
